version: '3'

services:
### Go Container #########################################
  chat-serve:
    build:
      context: ./project
    restart: on-failure
    ports:
      - "${GO_PORT}:8080"
    volumes:
      - "./project/log:/log"
    tty: true

networks:
  default:
    external:
      name: ${USER_NETWORK}
